import { AnimatePresence, motion, useReducedMotion } from "motion/react";
import { useUrlState } from "../hooks/useUrlState";
import Section from "./Section";
import { projects } from "../data/content";
import type { Project } from "../data/content";

const filters = ["All", "Security", "AI and ML", "Cloud", "Data"] as const;
type Filter = (typeof filters)[number];

/**
 * Abstract artwork per project, generated by scripts/make-art.mjs. The file is
 * white-on-transparent and used as a mask over the seasonal accent gradient,
 * so the same artwork recolours itself for every season and festival.
 * Deliberately not a screenshot; replace with a real capture when one exists.
 */
function Thumb({ p, tall }: { p: Project; tall?: boolean }) {
  const art = `url(/img/work/${p.slug}.webp)`;
  return (
    <div
      aria-hidden="true"
      className={`relative isolate overflow-hidden bg-bg-subtle ${
        tall ? "h-full min-h-[200px]" : "aspect-[3/1]"
      }`}
    >
      <div
        className="absolute inset-0"
        style={{
          background:
            "radial-gradient(90% 100% at 25% 15%, var(--color-accent-subtle), transparent 70%)",
        }}
      />
      <div
        className="absolute inset-0 transition-transform duration-700 ease-out group-hover:scale-[1.06]"
        style={{
          background: "linear-gradient(120deg, var(--color-accent), var(--color-second))",
          WebkitMaskImage: art,
          maskImage: art,
          WebkitMaskSize: "cover",
          maskSize: "cover",
          WebkitMaskPosition: "center",
          maskPosition: "center",
          WebkitMaskRepeat: "no-repeat",
          maskRepeat: "no-repeat",
          opacity: 0.9,
        }}
      />
      {/* Fade toward the copy: sideways on the tall featured panel, upward on the wide band. */}
      <div
        className={`absolute inset-0 ${
          tall
            ? "bg-gradient-to-r from-transparent from-60% to-bg-elevated"
            : "bg-gradient-to-t from-bg-elevated/90 via-transparent to-transparent"
        }`}
      />
    </div>
  );
}

function Meta({ p }: { p: Project }) {
  return (
    <p className="font-mono text-[12px] text-fg-subtle">
      {p.context}
      <span className="mx-2 text-line-strong">/</span>
      {p.year}
    </p>
  );
}

function Stack({ p }: { p: Project }) {
  return (
    <ul className="mt-5 flex flex-wrap gap-1.5">
      {p.stack.map((s) => (
        <li
          key={s}
          className="rounded-[4px] border border-line bg-bg px-2 py-1 font-mono text-[11.5px] text-fg-muted"
        >
          {s}
        </li>
      ))}
    </ul>
  );
}

export default function Projects() {
  const [filter, setFilter] = useUrlState<Filter>("work", filters, "All");
  const reduce = useReducedMotion();
  const visible = projects.filter((p) => filter === "All" || p.category === filter);

  return (
    <Section
      id="work"
      title="Selected"
      accent="work"
      glow="right"
      lede="Coursework, capstones, and a home lab that never quite finishes. Each one lists what I actually owned."
    >
      <div role="group" aria-label="Filter projects" className="mb-8 flex flex-wrap gap-2">
        {filters.map((f) => (
          <button
            key={f}
            onClick={() => setFilter(f)}
            aria-pressed={filter === f}
            className={`btn-shape border px-3.5 py-1.5 text-[13.5px] ${
              filter === f
                ? "border-accent bg-accent text-accent-fg"
                : "border-line text-fg-muted hover:border-accent/50 hover:text-fg"
            }`}
          >
            {f}
          </button>
        ))}
      </div>

      <motion.div layout={!reduce} className="grid gap-4 md:grid-cols-2">
        <AnimatePresence mode="popLayout">
          {visible.map((p) => (
            <motion.article
              key={p.slug}
              layout={!reduce}
              initial={reduce ? false : { opacity: 0, scale: 0.97 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={reduce ? { opacity: 0 } : { opacity: 0, scale: 0.97 }}
              transition={{ duration: 0.3, ease: [0.16, 1, 0.3, 1] }}
              className={`spotlight lift group overflow-hidden rounded-[10px] border border-line bg-bg-elevated transition-colors hover:border-accent/40 ${
                p.featured ? "md:col-span-2" : ""
              }`}
              onPointerMove={(e) => {
                // Feeds the CSS spotlight border without re-rendering.
                const r = e.currentTarget.getBoundingClientRect();
                e.currentTarget.style.setProperty("--mx", `${e.clientX - r.left}px`);
                e.currentTarget.style.setProperty("--my", `${e.clientY - r.top}px`);
              }}
            >
              {p.featured ? (
                <div className="grid md:grid-cols-[minmax(0,0.68fr)_minmax(0,1.32fr)]">
                  <Thumb p={p} tall />
                  <div className="p-6 sm:p-8">
                    <Meta p={p} />
                    <h3 className="mt-3 text-2xl font-semibold tracking-tight text-fg sm:text-[1.75rem]">
                      {p.title}
                    </h3>
                    <p className="mt-1 text-[15px] font-medium text-accent">{p.blurb}</p>
                    <p className="mt-4 max-w-[62ch] text-[14.5px] leading-relaxed text-fg-muted">
                      {p.body}
                    </p>
                    <p className="mt-4 font-mono text-[12px] text-fg-subtle">{p.role}</p>
                    <Stack p={p} />
                  </div>
                </div>
              ) : (
                <div className="flex h-full flex-col">
                  <Thumb p={p} />
                  <div className="flex flex-1 flex-col p-6">
                    <Meta p={p} />
                    <h3 className="mt-3 text-xl font-semibold tracking-tight text-fg">{p.title}</h3>
                    <p className="mt-1 text-[14px] font-medium text-accent">{p.blurb}</p>
                    <p className="mt-3 text-[14.5px] leading-relaxed text-fg-muted">{p.body}</p>
                    <p className="mt-4 font-mono text-[12px] text-fg-subtle">{p.role}</p>
                    <div className="mt-auto">
                      <Stack p={p} />
                    </div>
                  </div>
                </div>
              )}
            </motion.article>
          ))}
        </AnimatePresence>
      </motion.div>

      {visible.length === 0 && (
        <p className="rounded-[10px] border border-dashed border-line-strong p-10 text-center text-fg-muted">
          Nothing in that category yet.
        </p>
      )}
    </Section>
  );
}
